"""Public API for the NextGen Memory kernel."""

from .domain import (
    EvidenceNeed,
    ExactnessNeed,
    ExpertAllocation,
    ExpertKey,
    MemoryCandidate,
    PlanPhase,
    RiskLevel,
    RoutingDecision,
    RoutingRequest,
    RoutingScope,
    Sensitivity,
    TaskKind,
    TemporalIntent,
)
from .eligibility import EligibilityResult, evaluate_candidate_eligibility
from .router import DeterministicMemoryRouter
from .state import (
    ProjectionVerification,
    StateProjection,
    StateProjectionVerification,
    StateReplayError,
    StateResolutionEvent,
    StateStatus,
    StateVerdict,
    StoredStateSlot,
    apply_state_resolution,
    replay_state,
    replay_state_slots,
    verify_state_projection,
)
from .telemetry import (
    InMemoryRoutingDecisionSink,
    RoutingDecisionSink,
    RoutingTelemetryRecord,
)

__all__ = [
    "DeterministicMemoryRouter",
    "EligibilityResult",
    "EvidenceNeed",
    "ExactnessNeed",
    "ExpertAllocation",
    "ExpertKey",
    "InMemoryRoutingDecisionSink",
    "MemoryCandidate",
    "PlanPhase",
    "ProjectionVerification",
    "RiskLevel",
    "RoutingDecision",
    "RoutingDecisionSink",
    "RoutingRequest",
    "RoutingScope",
    "RoutingTelemetryRecord",
    "Sensitivity",
    "StateProjection",
    "StateProjectionVerification",
    "StateReplayError",
    "StateResolutionEvent",
    "StateStatus",
    "StateVerdict",
    "StoredStateSlot",
    "TaskKind",
    "TemporalIntent",
    "apply_state_resolution",
    "evaluate_candidate_eligibility",
    "replay_state",
    "replay_state_slots",
    "verify_state_projection",
]
